title: Education
baseurl: /
theme: hugo-graphite
googleAnalytics: ''
relativeurls: no
languageCode: en-us
description: An opinionated collection of R packages designed for data science.
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - _files$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md
preserveTaxonomyNames: yes
permalinks:
  blog: blog/:year/:month/:slug/
taxonomies:
  author: author
  category: categories
  tag: tags
blackfriday:
  angledQuotes: no
  extensions: backslashLineBreak
  hrefTargetBlank: yes
  latexDashes: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: pygments
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
